# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='photo',
            field=models.ImageField(upload_to=photo.models.upload_location),
        ),
    ]
